#!/usr/bin/env bash
set -euo pipefail

# import-cases.sh
# Validate and import TestRail add_case payloads generated by the E2E Test Creator agent.
# Dry-run by default; nothing is sent to TestRail unless --apply is given.
#
# Usage: import-cases.sh <testrail-cases.json> [--section-id ID] [--only ID1,ID2] [--apply] [--allow-unresolved]
#
# Input file: JSON array of { "scenarioId", "sectionId", "payload": { add_case body } }
# --section-id overrides every entry's sectionId.
# Unresolved markers (?...?, [TBD], <TBD...>) are reported as warnings; --apply refuses
# to import them unless --allow-unresolved is given.
#
# Environment Variables (only needed with --apply):
#   TESTRAIL_URL      - TestRail instance URL (e.g. https://yourcompany.testrail.io)
#   TESTRAIL_USER     - TestRail username (email)
#   TESTRAIL_API_KEY  - TestRail API key
#
# Results: created case IDs are written to <file>.results.json; scenarios already
# listed there are skipped on re-runs.
#
# Examples:
#   ./import-cases.sh reports/LOYALTY-OFFERS/testrail-cases-LOYALTY-OFFERS.json --section-id 0
#   ./import-cases.sh reports/LOYALTY-OFFERS/testrail-cases-LOYALTY-OFFERS.json --section-id 1234 --apply

MAX_RETRIES=3
RETRY_DELAY=5

show_usage() {
    echo "Usage: $0 <testrail-cases.json> [--section-id ID] [--only ID1,ID2] [--apply] [--allow-unresolved]"
    exit 1
}

[[ $# -lt 1 ]] && show_usage
command -v jq >/dev/null || { echo "Error: jq is required" >&2; exit 1; }

FILE="$1"; shift
SECTION_OVERRIDE=""
ONLY=""
APPLY=false
ALLOW_UNRESOLVED=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --section-id) SECTION_OVERRIDE="${2:-}"; shift 2 ;;
        --only) ONLY="${2:-}"; shift 2 ;;
        --apply) APPLY=true; shift ;;
        --allow-unresolved) ALLOW_UNRESOLVED=true; shift ;;
        *) show_usage ;;
    esac
done

[[ -f "$FILE" ]] || { echo "Error: file not found: $FILE" >&2; exit 1; }
jq empty "$FILE" 2>/dev/null || { echo "Error: $FILE is not valid JSON" >&2; exit 1; }
[[ -z "$SECTION_OVERRIDE" || "$SECTION_OVERRIDE" =~ ^[0-9]+$ ]] || { echo "Error: --section-id must be numeric" >&2; exit 1; }

RESULTS="${FILE%.json}.results.json"
results_json() { if [[ -f "$RESULTS" ]]; then cat "$RESULTS"; else echo '[]'; fi; }

# Structural validation of every entry
ERRORS=$(jq -r '
  if type != "array" then "root: must be a JSON array" else
  to_entries[] | .key as $i | .value as $e |
  ( [ (if ($e.scenarioId | type) != "string" then "scenarioId missing" else empty end),
      (if ($e.payload.title | type) != "string" or ($e.payload.title | length) == 0 then "payload.title missing" else empty end),
      (if ($e.payload.title // "" | length) > 250 then "payload.title > 250 chars" else empty end),
      (if ($e.payload.refs // "" | length) > 250 then "payload.refs > 250 chars" else empty end),
      (if ($e.payload.custom_preconds | type) != "string" then "payload.custom_preconds missing" else empty end),
      (if ($e.payload.custom_steps_separated | type) != "array" or ($e.payload.custom_steps_separated | length) == 0 then "payload.custom_steps_separated empty" else empty end),
      ($e.payload.custom_steps_separated // [] | to_entries[] |
        (if (.value.content // "" | test("^WHEN "; "")) | not then "step \(.key + 1): content must start with WHEN" else empty end),
        (if (.value.expected // "" | test("^THEN "; "")) | not then "step \(.key + 1): expected must start with THEN" else empty end))
    ] | .[] | "entry \($i) (\($e.scenarioId // "?")): \(.)" )
  end' "$FILE")

DUP_TITLES=$(jq -r '[.[].payload.title] | group_by(.) | map(select(length > 1) | .[0]) | .[]' "$FILE")
[[ -n "$DUP_TITLES" ]] && ERRORS="${ERRORS}${ERRORS:+$'\n'}duplicate titles: ${DUP_TITLES//$'\n'/, }"

if [[ -n "$ERRORS" ]]; then
    echo "Validation failed:" >&2
    echo "$ERRORS" >&2
    exit 1
fi

# Unresolved expectation markers: warnings, blocking only for --apply
WARNINGS=$(jq -r '
  to_entries[] | .key as $i | .value as $e |
  ([$e.payload.custom_preconds, ($e.payload.custom_steps_separated[]? | .content, .expected)]
    | map(select(type == "string")) | join("\n")
    | [scan("\\?[^?\n]+\\?|\\[TBD[^\\]]*\\]|<TBD[^>]*>")]) as $m |
  select($m | length > 0) |
  "entry \($i) (\($e.scenarioId)): \($m | length) unresolved: \($m | join("; "))"' "$FILE")

TOTAL=$(jq 'length' "$FILE")
echo "Validated $TOTAL case(s) in $FILE"
if [[ -n "$WARNINGS" ]]; then
    echo ""
    echo "Warnings (unresolved expectations):"
    echo "$WARNINGS"
fi
echo ""
printf "%-28s %-8s %-9s %s\n" "SCENARIO" "SECTION" "ACTION" "TITLE"

PLAN=()
PLAN_COUNT=0
for i in $(seq 0 $((TOTAL - 1))); do
    ID=$(jq -r ".[$i].scenarioId" "$FILE")
    TITLE=$(jq -r ".[$i].payload.title" "$FILE")
    SID="${SECTION_OVERRIDE:-$(jq -r ".[$i].sectionId // empty" "$FILE")}"

    if [[ -n "$ONLY" && ",$ONLY," != *",$ID,"* ]]; then
        ACTION="skip"
    elif results_json | jq -e --arg id "$ID" 'any(.[]; .scenarioId == $id)' >/dev/null; then
        ACTION="exists"
    elif [[ ! "$SID" =~ ^[0-9]+$ ]]; then
        echo "Error: $ID has no numeric sectionId; pass --section-id" >&2
        exit 1
    else
        ACTION="create"
        PLAN+=("$i:$SID")
        PLAN_COUNT=$((PLAN_COUNT + 1))
    fi
    printf "%-28s %-8s %-9s %s\n" "$ID" "${SID:--}" "$ACTION" "$TITLE"
done

echo ""
if [[ "$APPLY" != true ]]; then
    echo "Dry run: ${PLAN_COUNT} case(s) would be created. Re-run with --apply to import."
    exit 0
fi

[[ $PLAN_COUNT -eq 0 ]] && { echo "Nothing to import."; exit 0; }
if [[ -n "$WARNINGS" && "$ALLOW_UNRESOLVED" != true ]]; then
    echo "Error: unresolved expectations listed above. Resolve them, or re-run with --allow-unresolved." >&2
    exit 1
fi
for v in TESTRAIL_URL TESTRAIL_USER TESTRAIL_API_KEY; do
    [[ -n "${!v:-}" ]] || { echo "Error: $v environment variable not set" >&2; exit 1; }
done

post_case() {
    local sid="$1" body="$2" attempt=1 response http_code
    while [[ $attempt -le $MAX_RETRIES ]]; do
        response=$(curl -s -w "\n%{http_code}" -X POST \
            -u "${TESTRAIL_USER}:${TESTRAIL_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$body" \
            "${TESTRAIL_URL%/}/index.php?/api/v2/add_case/${sid}")
        http_code=$(echo "$response" | tail -n1)
        response=$(echo "$response" | sed '$d')
        if [[ "$http_code" == "200" ]]; then
            echo "$response"
            return 0
        elif [[ "$http_code" == "429" ]]; then
            echo "Rate limited. Retrying in ${RETRY_DELAY}s (attempt $attempt/$MAX_RETRIES)..." >&2
            sleep "$RETRY_DELAY"
            attempt=$((attempt + 1))
        else
            echo "Error: HTTP $http_code" >&2
            echo "$response" >&2
            return 1
        fi
    done
    echo "Error: Max retries exceeded" >&2
    return 1
}

CREATED=0
for item in "${PLAN[@]}"; do
    i="${item%%:*}"; SID="${item#*:}"
    ID=$(jq -r ".[$i].scenarioId" "$FILE")
    BODY=$(jq -c ".[$i].payload" "$FILE")
    if ! RESP=$(post_case "$SID" "$BODY"); then
        echo "Stopped at $ID. Created $CREATED case(s) before the failure; see $RESULTS." >&2
        exit 1
    fi
    CASE_ID=$(echo "$RESP" | jq -r '.id')
    TMP=$(mktemp)
    results_json | jq --arg id "$ID" --argjson cid "$CASE_ID" --argjson sid "$SID" \
        '. + [{scenarioId: $id, testrailCaseId: $cid, sectionId: $sid}]' > "$TMP" && mv "$TMP" "$RESULTS"
    CREATED=$((CREATED + 1))
    echo "Created C${CASE_ID} for $ID"
done

echo ""
echo "Imported $CREATED case(s). Results: $RESULTS"
